### ISSUE TITLE
can't run a script(((

### ISSUE THREAD

**Issue by midi-creator** [Havrevoll/md#1]
Greetings, install  bitstring

and....

C:\Users\1\AppData\Local\Programs\Python\Python312>python.exe toc.py toc.bin example.cue
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\toc.py", line 33, in <module>
    seconds = read_cuefile(Path(args.cuefile))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\toc.py", line 13, in read_cuefile
    for l in f:
             ^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 317: character maps to <undefined>

**Comment by midi-creator** [comment]
helpppp....

**Comment by midi-creator** [comment]
first cue then bin python toc.py p.cue toc.bin 
in this order works

**Comment by Havrevoll** [comment]
Hello, I'm sorry, I was busy this evening, but it seems you found a solution. I will have a look at it myself tomorrow morning. The script is very crude and not sophisticated, so please bear over if it's a little cumbersome to use. With time I will try to make it more robust and flexible.

**Comment by midi-creator** [comment]
Yes, thank you for your hard work!
It's working perfectly
how to extract the timing information?
What is cuebreakpoints? another script for python?

**Comment by midi-creator** [comment]
while I was manually extracting the timing from cue
